CREATE TABLE 'student' (
	'id' VARCHAR(10) NOT NULL,
    'name' VARCHAR(255) NOT NULL,
	'email' VARCHAR(255) NOT NULL,
	'password' VARCHAR(255) NOT NULL,
	'city' VARCHAR(30),
	'address' VARCHAR(255),
	'phonenumber' VARCHAR(255) NOT NULL,
	UNIQUE KEY 'index1' ('id') USING BTREE,
	PRIMARY KEY ('id')
);

CREATE TABLE admin (
	id VARCHAR(10) NOT NULL,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE region (
	id VARCHAR(5) NOT NULL,
	region VARCHAR(50) NOT NULL,
	createdBy VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);