#!/bin/sh

# Run Prettier to format code
npm run prettier

# Check if Prettier succeeded
if [ $? -ne 0 ]; then
  echo "Prettier failed. Aborting push."
  exit 1
fi

# If everything is fine, allow the push to proceed
exit 0